import numpy as np

class Solver:
    def __init__(self, points: np.ndarray, cells: np.ndarray, boundaries: np.ndarray) -> None:...
    def setting_density(self, density: float) -> None:...
    def setting_specific_heat(self, specific_heat: float) -> None:...
    def setting_conductivity(self, conductivity: list) -> None:...
    def setting_heat_transfer_coefficient(self, h: float) -> None:...
    def setting_environment_temperature(self, temperature: float) -> None:...
    def setting_initial_temperature(self, temperature: float) -> None:...
    def setting_num_process(self, num_process: int) -> None:...
    def setting_element_type(self, element_type: str) -> None:...
    def setting_total_time(self, total_time: float) -> None:...
    def setting_time_step(self, time_step: float) -> None:...
    def solve(self) -> np.ndarray:...
